services:
  # --- BANCO DE DADOS ---
  db:
    image: mysql:latest
    container_name: coinflip_db
    restart: always
    # Aqui usamos as variáveis do .env para configurar o container do MySQL em si
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # --- APLICAÇÃO DJANGO ---
  web:
    build: ./app
    container_name: coinflip_web
    restart: always
    working_dir: /app/Projeto_1_Nuvem
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 MyProject.wsgi:application
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    # A MÁGICA ACONTECE AQUI:
    # Isso carrega todo o arquivo .env para dentro do Linux desse container.
    # O Python vai conseguir ler tudo com os.getenv()
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

  # --- NGINX ---
  nginx:
    image: nginx:latest
    container_name: coinflip_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/coinflip.com/staticfiles:ro
      - media_volume:/var/www/coinflip.com/mediafiles:ro
    depends_on:
      - web
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:
  db_data:

networks:
  app_network:
    driver: bridge